[package]
name = "video-metadata-cleaner"
version = "0.1.0"
description = "Remove video metadata without re-encoding"
authors = ["you"]
edition = "2021"

[lib]
name = "video_metadata_cleaner_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-shell = "2"
